/**:
  ros__parameters:
    # TODO: 用户填写实际标定板参数
    squares_x: 5           # 棋盘格列数
    squares_y: 7           # 棋盘格行数
    square_length: 0.033    # 方格边长 (米)
    marker_length: 0.02    # ArUco标记边长 (米)
    dictionary: "5x5_100"  # ArUco字典类型

# 长10.1+13.5=23.6
# 宽：10.1+6.7=16.8
# 小的2cm   大的3.3